### ISSUE TITLE
一个小小的笔误吧

### ISSUE THREAD

**Issue by Smile-zjk** [dragen1860/Deep-Learning-with-TensorFlow-book#10]
![image](https://user-images.githubusercontent.com/41987902/68943748-0622b880-07e7-11ea-86a3-ae6e2845d58e.png)

pdf第59页“如果采用tf.float32精度保存π，可获得更高的精度“  应该是tf.float64，可能是笔误了，无伤大雅，希望以后的版本能够修改过来

**Comment by dragen1860** [comment]
收到，谢谢您！
