### ISSUE TITLE
P9 第二章4. 梯度更新     返回最优b, w 的代码有误

### ISSUE THREAD

**Issue by NormanBeita** [dragen1860/Deep-Learning-with-TensorFlow-book#106]
# 训练优化1000次，返回最优w*,b*和训练Loss的下降过程
[b, w], losses = gradient_descent(data, initial_b, initial_w, lr, num_it erations)

但gradient_descent函数return的只是[b,w]

**Comment by dragen1860** [comment]
收到！谢谢。
