### ISSUE TITLE
第五章 5.5 数据限幅 P12

### ISSUE THREAD

**Issue by NormanBeita** [dragen1860/Deep-Learning-with-TensorFlow-book#107]
那么 ReLU 函数可以实现为:
通过组合 tf.maximum(x, a)和 tf.minimum(x, b)可以实现同时对数据的上下边界限幅: 𝑥 ∈ [𝑎, 𝑏]:
def relu(x):
return tf.minimum(x,0.) # 下限幅为 0 即可
 
下限幅函数是maximun, 此处应改为return tf.maximun(x,0.)

**Comment by dragen1860** [comment]
收到！谢谢。
