### ISSUE TITLE
第 5 章 5.6 P22 

### ISSUE THREAD

**Issue by NormanBeita** [dragen1860/Deep-Learning-with-TensorFlow-book#108]
通过 matplotlib 即可绘制出函数在𝑥 ∈ [−8,8], 𝑦 ∈ [−8,8]区间的 3D 曲面，如图 5.5 中所示:
fig = plt.figure()
ax = Axes3D(fig)
这段代码是不是最好把import部分打出来？
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.axes3d import Axes3D / from mpl_toolkits.mplot3d import Axes3D

**Comment by dragen1860** [comment]
收到！谢谢。
