### ISSUE TITLE
第四章，4.9.3，P33

### ISSUE THREAD

**Issue by philipxue39** [dragen1860/Deep-Learning-with-TensorFlow-book#109]
x = tf.constant([1.,2.])
x = 10**x
tf.math.log(x)/tf.math.log(10.)
输出有些问题，应该是和最开始的输入一样。
<tf.Tensor: id=252, shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>
![Snipaste_2019-12-04_17-34-48](https://user-images.githubusercontent.com/58508952/70130977-7d4bbe00-16bc-11ea-88fe-4b0668db5b6e.png)

**Comment by dragen1860** [comment]
这个输出估计搞混了，代码可以的。
谢谢。
