### ISSUE TITLE
5.7.1 随机打散 P23

### ISSUE THREAD

**Issue by NormanBeita** [dragen1860/Deep-Learning-with-TensorFlow-book#110]
其中 buffer_size 指定缓冲池的大小，一般设置为一个较大的参数即可。通过 Dataset 提供的
这些工具函数会返回新的 Dataset 对象，可以通过
db = db. shuffle(). step2(). step3. ()

如果可以的话，这段话是不是要解释清楚点比较好

和源码参照了一下，db指的是train_db 和test_db 都需要这种操作，step2(). step3. ()指的是5.7.2batch和5.7.3map(preprocess)流程？

**Comment by NormanBeita** [comment]
5.8 MNIST 测试实战 P25 
train_db = train_db.repeat(20) # 数据集跌打 20 遍才终止
是迭代不是跌打。。。

**Comment by dragen1860** [comment]
step2 step3是一些数据集的处理步骤，可以是任意的合法函数。
收到，谢谢！
