### ISSUE TITLE
ch13:toimage函数已经取消，无法使用

### ISSUE THREAD

**Issue by WangJinBinaiChenJun** [dragen1860/Deep-Learning-with-TensorFlow-book#111]
ch13中的scipy库
`from    scipy.misc import toimage`
其中的toimage函数已经没有了
可以改为使用
`from PIL import Image`
40行的
` toimage(final_image).save(image_path)`
可更改为
` Image.fromarray(final_image).save(image_path)`

**Comment by dragen1860** [comment]
收到，谢谢！
