### ISSUE TITLE
tf.split() 函数5.1.2  P96

### ISSUE THREAD

**Issue by YuanchenHua** [dragen1860/Deep-Learning-with-TensorFlow-book#113]
tf.split() [官方文档](https://tensorflow.google.cn/api_docs/python/tf/split) 参数顺序是`value,num_or_size_splits,axis=0,num=None,name='split'` 书中是`value,axis,num_or_size_splits,num=None,name='split'` 在不指定参数名传参的时候，用书中的顺序会报错。

**Comment by YuanchenHua** [comment]
此类情况好多，我建议在介绍函数的时候，如果是关键字参数，还是在一开始介绍的时候，把`关键字参数=默认值`写上，避免初学者把必须参数和关键字参数混淆。

**Comment by dragen1860** [comment]
收到，谢谢！
