### ISSUE TITLE
P3,关于constant布尔类型

### ISSUE THREAD

**Issue by Baytwt** [dragen1860/Deep-Learning-with-TensorFlow-book#114]
`a = tf.constant(True) # 布尔类型  

print(a)  

print(a == True)`  

输出:

tf.Tensor(True, shape=(), dtype=bool)

tf.Tensor(True, shape=(), dtype=bool)

按照书上说的,第二个输出应该是False呀

**Comment by dragen1860** [comment]
收到，谢谢！
