### ISSUE TITLE
6.8 油耗预测实战 P22

### ISSUE THREAD

**Issue by NormanBeita** [dragen1860/Deep-Learning-with-TensorFlow-book#116]
![image](https://user-images.githubusercontent.com/28737120/70320100-d5bac100-185e-11ea-9cd8-f7720d215f35.png)

这段与实际代码是反的，'MPG' 已经被pop掉的话，后边怎么可能还在describe中再pop一次，这种逻辑错误有点低级。

**Comment by dragen1860** [comment]
你好，这个地方其实是为了演示pop前后的区别，
