### ISSUE TITLE
第十一章 RNN情感分类问题实战代码编译出错 P288

### ISSUE THREAD

**Issue by BruceWeiii** [dragen1860/Deep-Learning-with-TensorFlow-book#127]
环境：python3.7，tensorflow2.0.0

model.fit(db_train, epochs=epochs, validation_data=db_test)
该句代码出错：
TypeError: call() takes 2 positional arguments but 3 were given

**Comment by JK2016ASDF** [comment]
我也遇到了， 你解决了吗？
