### ISSUE TITLE
tf.data.Dataset.from_tensor_slices

### ISSUE THREAD

**Issue by Julius-ZCJ** [dragen1860/Deep-Learning-with-TensorFlow-book#133]
1. train_db = tf.data.Dataset.from_tensor_slices（）这个函数是什么作用，我查了官网只说：Creates a Dataset whose elements are slices of the given tensors， 还是不明白他对数据做了什么，可以解释下么？
2. train_db.shuffle(1000) 中的参数1000是代表打乱1000次么？这和没有参数有什么区别？

**Comment by YuanchenHua** [comment]
> 1. train_db = tf.data.Dataset.from_tensor_slices（）这个函数是什么作用，我查了官网只说：Creates a Dataset whose elements are slices of the given tensors， 还是不明白他对数据做了什么，可以解释下么？
> 2. train_db.shuffle(1000) 中的参数1000是代表打乱1000次么？这和没有参数有什么区别？

把数据x,y组合在一起,变成可迭代的一组组.你print一下结果,看看属性,shape就能明白了
[shuffle()](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?version=stable#shuffle)的官方文档,1000是buffer_size 
原文:
This dataset fills a buffer with buffer_size elements, then randomly samples elements from this buffer, replacing the selected elements with new elements. For perfect shuffling, a buffer size greater than or equal to the full size of the dataset is required.

For instance, if your dataset contains 10,000 elements but buffer_size is set to 1,000, then shuffle will initially select a random element from only the first 1,000 elements in the buffer. Once an element is selected, its space in the buffer is replaced by the next (i.e. 1,001-st) element, maintaining the 1,000 element buffer.
比如,总数据100个,buffer_size = 10,就是每10个取1个,这样打乱,原来0~99的话,我打乱,0~9我取一个,10~19我取一个
希望有所帮助

**Comment by Julius-ZCJ** [comment]
@YuanchenHua 谢谢答疑，我大概知道了，但是我看你的回答是不是理解错了，我的理解是：从前1000个中取出一个，然后用后一个代替他的位置，也就是将取出的数据删除，在从剩余的数据中选出一个数据代替取出的数据，在做随机抽取。都是在前1000内抽。不知道是你理解错了还是我错了。

**Comment by YuanchenHua** [comment]
> @YuanchenHua 谢谢答疑，我大概知道了，但是我看你的回答是不是理解错了，我的理解是：从前1000个中取出一个，然后用后一个代替他的位置，也就是将取出的数据删除，在从剩余的数据中选出一个数据代替取出的数据，在做随机抽取。都是在前1000内抽。不知道是你理解错了还是我错了。

你对的,就是1000个相当于抽奖箱. 在着1000里面随机抽,抽走了,少了,就后面的按顺序补上.没仔细看.
