### ISSUE TITLE
3.8.2代码有错误

### ISSUE THREAD

**Issue by maihao14** [dragen1860/Deep-Learning-with-TensorFlow-book#136]
在上文中 变量y已经是one-hot 形式
因此，此处
with tf.GradientTape() as tape:
    y_onehot = tf.one_hot(y, depth=10)  #此处会产生报错

建议更改，以免初学者产生疑惑（ y_onehot = y）
另外此段后
自动计算梯度
更新网络参数 
两部分也无法编译通过，参数变量未定义

**Comment by dragen1860** [comment]
收到，谢谢。
