### ISSUE TITLE
15.4.2 迁移学习实战 代码部分第2个注释，原为”设计为不参与优化“，应改为“设置为不参与优化”

### ISSUE THREAD

**Issue by gfanqi** [dragen1860/Deep-Learning-with-TensorFlow-book#142]
15.4.2 迁移学习实战 代码部分第2个注释，原为”设计为不参与优化“，应改为“设置为不参与优化”，net.trainable设置为false

# 加载 DenseNet 网络模型，并去掉最后一层全连接层，最后一个池化层设置为 max pooling
net = keras.applications.DenseNet121(weights='imagenet', include_top=False,
pooling='max')
# 设计为不参与优化，即 MobileNet 这部分参数固定不动
net.trainable = True

**Comment by dragen1860** [comment]
收到，谢谢。
