### ISSUE TITLE
第十五章下载数据集时，打开网址，显示404

### ISSUE THREAD

**Issue by cymx66688** [dragen1860/Deep-Learning-with-TensorFlow-book#143]
https://www.pyimagesearch.com/2018/04/16/keras-and-convolutional-neuralnetworks-cnns/

![image](https://user-images.githubusercontent.com/44802959/71807352-14ce7300-30a6-11ea-8dea-bbf303a4f2c1.png)

是否可以把数据集放在百度网盘，供大家下载。

**Comment by dragen1860** [comment]
https://github.com/dragen1860/TensorFlow-2.x-Tutorials/tree/master/%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0%E4%B8%8ETensorFlow%E5%85%A5%E9%97%A8%E5%AE%9E%E6%88%98-%E6%BA%90%E7%A0%81%E5%92%8CPPT/lesson52-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86%E5%92%8C%E8%BF%81%E7%A7%BB%E5%AD%A6%E4%B9%A0
这里的PPT上面有下载链接。
