### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by Haojin-Hu** [dragen1860/Deep-Learning-with-TensorFlow-book#152]
第六页第一段：比第二名在Top-5 错误率上降低了惊人的10.9%，。

多了一个逗号

**Comment by zenglian** [comment]
你看的版本太老了。看新版，多收集一点再report，别一个逗号提一个issue。

**Comment by Haojin-Hu** [comment]
> 第六页第一段：比第二名在Top-5 错误率上降低了惊人的10.9%，。
> 
> 多了一个逗号
