### ISSUE TITLE
请求更新tensorflow安装部分

### ISSUE THREAD

**Issue by Wings-Fantasy** [dragen1860/Deep-Learning-with-TensorFlow-book#177]
目前为止tf最新版2.1，CPU和GPU软件包不再是分开的了。直接使用：pip install tensorflow就可以了，现在如果使用：pip install tensorflow-gpu的话是会报错提示找不到的。

**Comment by dragen1860** [comment]
我的可以找到。
![image](https://user-images.githubusercontent.com/4252555/79870113-0b7ad380-8415-11ea-8249-c689d5e5a2b5.png)

**Comment by dragen1860** [comment]
收到，谢谢！
