### ISSUE TITLE
宝可梦数据集 下载不了

### ISSUE THREAD

**Issue by AlienTQH** [dragen1860/Deep-Learning-with-TensorFlow-book#180]
请问可以发一 宝可梦数据集 数据集吗或者下载链接吗

**Comment by AlienTQH** [comment]
找到了
链接：https://pan.baidu.com/s/19aSoEvILdxdXK1v-5clGNg 提取码：7vt9

**Comment by youngstar9** [comment]
> 找到了
> 链接：https://pan.baidu.com/s/19aSoEvILdxdXK1v-5clGNg 提取码：7vt9

thank you
