### ISSUE TITLE
油耗预测input_shape

### ISSUE THREAD

**Issue by Stark-Chang** [dragen1860/Deep-Learning-with-TensorFlow-book#186]
model.build(input_shape=(None,9))

input_shape 怎么写？我看官方文档是数据的大小，不包含批次。油耗数据处理完是(32,9)32是批次维，所以要改成None吗？
那输入数据批次处理完是（32，10，9），input_shape是（None，10，9）还是（10，9）？

**Comment by aesdhj** [comment]
同问，我也不太理解
建立一个QQ群805370297，方便大家一起讨论

**Comment by dragen1860** [comment]
batch size写成None还是具体的数字都一样。在动态图中，None失去了意义。
