### ISSUE TITLE
PDF开源书第6.8.1数据集节 有代码的下载链接是404-not found

### ISSUE THREAD

**Issue by li-changgen** [dragen1860/Deep-Learning-with-TensorFlow-book#188]
# 在线下载汽车效能数据集
dataset_path = keras.utils.get_file("auto-mpg.data",
"http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/autompg.
data")
上面的链接运行结果是404-not found
正确的链接是：http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg

**Comment by dragen1860** [comment]
VPN试试。

**Comment by li-changgen** [comment]
VPN 可以。没想到您还回复了，震惊！书写的非常好，感觉是我看到的目前对初学者最友好的深度学习入门书，谢谢您！
祝您工作顺利。

Best regard,

Changgen Li
PhD candidate
Southwest Jiaotong University
Chengdu,China

发件人: Jackie Loong
发送时间: 2020年5月30日 23:55
收件人: dragen1860/Deep-Learning-with-TensorFlow-book
抄送: Changgen Li; State change
主题: Re: [dragen1860/Deep-Learning-with-TensorFlow-book] PDF开源书第6.8.1数据集节 有代码的下载链接是404-not found (#188)

VPN试试。
