### ISSUE TITLE
WGAN-GP代码示例中哪里代表EM距离（菜鸟，求解答）

### ISSUE THREAD

**Issue by heqiang417** [dragen1860/Deep-Learning-with-TensorFlow-book#192]
或者怎么写出这个EM距离。
![image](https://user-images.githubusercontent.com/49976597/83324805-569cc780-a29a-11ea-8e80-1689f01f6910.png)
![image](https://user-images.githubusercontent.com/49976597/83324819-687e6a80-a29a-11ea-80a6-b615ba2ceefe.png)
![image](https://user-images.githubusercontent.com/49976597/83324828-6fa57880-a29a-11ea-9312-f1526469b16e.png)
![image](https://user-images.githubusercontent.com/49976597/83324833-759b5980-a29a-11ea-981d-edf6ad9998e9.png)

**Comment by dragen1860** [comment]
EM Dist是D需要学习的一个函数，并没有显式的表达式。
