### ISSUE TITLE
打开找不到

### ISSUE THREAD

**Issue by yuanchangwang** [dragen1860/Deep-Learning-with-TensorFlow-book#2]
试版(201911配套视频课程(收费，提供答疑等全方位服务，不喜勿喷)：
深度学习与 TensorFlow 入门实战 深度学习与 PyTorch 入门实战
https://study.163.com/course/courseMai
n.htm?share=2&shareId=48000000184
7407&courseId=1209092816&_trace_c
_p_k2_=9e74eb6f891d47cfaa6f00b5cb
5f617c
https://study.163.com/course/courseMain.htm?share=2&shareId=480000001847407&courseId=1208894818&_trace_c_p_k2_=8d1b10e04bd34d69855bb71da65b05

**Comment by dragen1860** [comment]
复制整个链接。
https://study.163.com/course/courseMain.htm?share=2&shareId=48000000184
7407&courseId=1209092816&_trace_c
p_k2=9e74eb6f891d47cfaa6f00b5cb
5f617c
