### ISSUE TITLE
书1.5.3节b)部分代码最后一行之前应加入“程序输出”的说明

### ISSUE THREAD

**Issue by AlohaWorld** [dragen1860/Deep-Learning-with-TensorFlow-book#20]
书中原文：

> 通过 TensorFlow 实现如下
> import tensorflow as tf
> # 创建4 个张量
> a = tf.constant(1.)
> b = tf.constant(2.)
> c = tf.constant(3.)
> w = tf.constant(4.)
> with tf.GradientTape() as tape:# 构建梯度环境
> tape.watch([w]) # 将w 加入梯度跟踪列表
> # 构建计算过程
> y = a * w**2 + b * w + c
> # 求导
> [dy_dw] = tape.gradient(y, [w])
> print(dy_dw) # 打印出导数
> tf.Tensor(10.0, shape=(), dtype=float32)
 
最后一行易令人误为程序内容。此行前应加入输出说明

**Comment by dragen1860** [comment]
收到，谢谢亲！
