### ISSUE TITLE
关于屏蔽tensorflow 2.0 warning的问题

### ISSUE THREAD

**Issue by CGrapher** [dragen1860/Deep-Learning-with-TensorFlow-book#22]
老师您好，刚刚听完您的视频教程，是我感觉讲的最好的一位，非常感谢。
由于现在tf2.0正式版已经发布，我安装的是正式版，按照您给出的代码（如下）中的方式屏蔽warning，似乎还会有一部分warning出现（如图）。
```
import  os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
```
![image](https://user-images.githubusercontent.com/24447496/69004852-887cbb00-0954-11ea-996a-656cb8e47f77.png)
我查阅了一些网站，发现在正式版tf2.0中，应该将屏蔽代码调整至tf的上方，warning就彻底没有了，不过对于代码运行无关紧要，算是个小疑问吧，再次感谢。
最终顺序：
```
import  os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import  tensorflow as tf
from    tensorflow import keras
from    tensorflow.keras import datasets
```

**Comment by dragen1860** [comment]
是这样子的，顺序比较关键。我们还没来得及全部改过来。谢谢亲！
