### ISSUE TITLE
1.4.2 百度驾驶汽车 Apollo翻译成中文应该是阿波罗

### ISSUE THREAD

**Issue by danerlt** [dragen1860/Deep-Learning-with-TensorFlow-book#25]
![image](https://user-images.githubusercontent.com/14197717/69036099-1ffb1000-0a20-11ea-8163-ef85ae1b3a61.png)
![image](https://user-images.githubusercontent.com/14197717/69036136-3012ef80-0a20-11ea-9cfa-904b5569e76a.png)

**Comment by hdhyy** [comment]
自动驾驶巴士确实是阿波龙，http://apollo.auto/minibus/index_cn.html

**Comment by danerlt** [comment]
原来百度就是这样叫的 感谢解答@hdhyy
