### ISSUE TITLE
4.1.3布尔类型那里，有错误

### ISSUE THREAD

**Issue by genius0182** [dragen1860/Deep-Learning-with-TensorFlow-book#27]
老师您好，我用的是tf2.0正式版，在运行4.1.3布尔类型这里面。
a = tf.constant(True)
a == True
这里，我的结果是可以通用的。下面是我的截图。
![2019-11-18 21-21-46屏幕截图](https://user-images.githubusercontent.com/24863486/69055740-7761a600-0a49-11ea-807f-ab13e13325db.png)

**Comment by dragen1860** [comment]
好的，我验证一下。谢谢！
