### ISSUE TITLE
P6 Line5  Goolenet->GoogleNet

### ISSUE THREAD

**Issue by wzh0105** [dragen1860/Deep-Learning-with-TensorFlow-book#29]
P15 Line5  Goolenet->GoogleNet
P35 倒数第4行 现象神经元->线性神经元

**Comment by dragen1860** [comment]
收到，谢谢亲！

**Comment by wzh0105** [comment]
P67 倒数第8行 fc = layers.Dense(3)是否应先声明导入keras包？或者使用tf.keras.layers？

**Comment by wzh0105** [comment]
P83 中间 至于怎么实现的用户不必关系->关心；对于用于来说->对于用户来说
P88 倒数第8行 [4,3,23,32]->[4,3,28,32]

**Comment by wzh0105** [comment]
P104 数据限幅 第二个tf.minimum(x, a)->过tf.maximum(x, a)

**Comment by wzh0105** [comment]
P117 Line7 数据集跌打20 遍

**Comment by wzh0105** [comment]
P121 Line1

**Comment by wzh0105** [comment]
P122 提出之处->提出之初

**Comment by dragen1860** [comment]
Cool
