### ISSUE TITLE
【《TensorFlow2深度学习》】.pdf  4.1.3 布尔类型 中的错误

### ISSUE THREAD

**Issue by yuanxiaosc** [dragen1860/Deep-Learning-with-TensorFlow-book#32]
原文”需要注意的是，TensorFlow 的布尔类型和Python语言的布尔类型并不对等，不能通用”，该局话最好加上，可以进行比较，且下面的例子是错误的。`tf.constant(True) == True` 的结果就是 `True`。

**Comment by dragen1860** [comment]
收到，谢谢！
