### ISSUE TITLE
运行CH15代码出现iCCP: known incorrect sRGB profile该如何解决

### ISSUE THREAD

**Issue by AlexYuu97** [dragen1860/Deep-Learning-with-TensorFlow-book#36]
老师您好，在运行CH15 自定义数据集的时候，出现了如下警告：
iCCP: known incorrect sRGB profile
虽然不影响程序，但是影响了观测训练，希望老师能够帮忙解决

**Comment by dragen1860** [comment]
这个警告你可以自己搜下，我们先修正重要问题，谢谢！
