### ISSUE TITLE
第67页，调用layers.Dense(), 需要加上tf.keras

### ISSUE THREAD

**Issue by ml2068** [dragen1860/Deep-Learning-with-TensorFlow-book#49]
第67页：
    fc = layers.Dense(3)  

 应修改为：
    fc=tf.keras.layers.Dense(3)

第68页：
    fc = layers.Dense(3) 
 应修改为：fc =tf.keras.layers.Dense(3)

**Comment by dragen1860** [comment]
为了简略，一般都是将layers提前导入的：from tensorflow.keras import layers。谢谢。
