### ISSUE TITLE
pycharm IDE cannot resolve module import tensorflow.keras

### ISSUE THREAD

**Issue by xautzxc** [dragen1860/Deep-Learning-with-TensorFlow-book#5]
then pyCharm cannot resolve module tf.keras and report an error:
Cannot find reference 'keras' in '__init__.py'
But when running program, everything works well.

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360002486739-PyCharm-cannot-import-tensorflow-keras

https://github.com/tensorflow/tensorflow/issues/26502

i follow this way , but it also didn't work well.
Is there anyways to solve it?
Thanks.

**Comment by dragen1860** [comment]
Yes, we all found it. But i think only can Google resolve this problem. Since it does have effect on running time, just ignore it.
