### ISSUE TITLE
第五章12页5.5 数据限幅 ReLU 函数

### ISSUE THREAD

**Issue by Stathamy** [dragen1860/Deep-Learning-with-TensorFlow-book#54]
原文：
那么 ReLU 函数可以实现为： 
def relu(x): 
    return tf.minimum(x,0.) # 下限幅为 0 即可 
改为:minimum->maximum

**Comment by Stathamy** [comment]
【错字】第五章25页5.7.4 循环训练 
倒数第二段：train_db = train_db.repeat(20) # 数据集跌打 20 遍才终止 
跌打->迭代

**Comment by dragen1860** [comment]
是的，谢谢你的发现！
