### ISSUE TITLE
2.3节拟合出的b与原给定真实值b相差太多

### ISSUE THREAD

**Issue by Lee1Thinker** [dragen1860/Deep-Learning-with-TensorFlow-book#59]
老师你好，书中2.3节线性模型实战，指定的真实模型为 
y = 1.477* x + 0.089 ，b = 0.089 但书中最后训练出迭代1000次后，b 值为0.901113270 与给定值相差
过多？ 自己运行了一下代码，b 位于0.1左右，这块是否出错了呢？

**Comment by grey2818** [comment]
我的也是0.1上下

**Comment by dragen1860** [comment]
可以试着调节一下超参数。我稍后更新一下。收到，谢谢！

**Comment by Lee1Thinker** [comment]
没事，很感谢你的工作和付出

在 2019-11-24 04:47:05，"Jackie Loong" <notifications@github.com> 写道：


可以试着调节一下超参数。我稍后更新一下。收到，谢谢！
