### ISSUE TITLE
第二章第四页错误

### ISSUE THREAD

**Issue by mHuaaa** [dragen1860/Deep-Learning-with-TensorFlow-book#60]
图 2.5 下的段落出现部分错误：
原文为“函数对自变量x的偏导数记为....， 函数对自变量x的偏导数记为...” 
应该改为：“函数对自变量x的偏导数记为....， 函数对自变量y的偏导数记为...”
即 第二个x改为y。

**Comment by dragen1860** [comment]
收到，谢谢！
