### ISSUE TITLE
P25，tf.Tensor(10.0, shape=(), dtype=float32)这看起来像一行代码

### ISSUE THREAD

**Issue by 2605759123** [dragen1860/Deep-Learning-with-TensorFlow-book#7]
import tensorflow as tf
# 创建 4 个张量
a = tf.constant(1.)
b = tf.constant(2.)
c = tf.constant(3.)
w = tf.constant(4.)
with tf.GradientTape() as tape:# 构建梯度环境
tape.watch([w]) # 将 w 加入梯度跟踪列表
# 构建计算过程
y = a * w**2 + b * w + c
# 求导
[dy_dw] = tape.gradient(y, [w])
print(dy_dw) # 打印出导数
tf.Tensor(10.0, shape=(), dtype=float32)

最后一行
tf.Tensor(10.0, shape=(), dtype=float32)
中，这本应是一个输出，但是没有特殊标明，也没有和前面的代码之间空一行，希望可以标明一下。

**Comment by 2605759123** [comment]
`import tensorflow as tf
# 创建 4 个张量
a = tf.constant(1.)
b = tf.constant(2.)
c = tf.constant(3.)
w = tf.constant(4.)
with tf.GradientTape() as tape:# 构建梯度环境
tape.watch([w]) # 将 w 加入梯度跟踪列表
# 构建计算过程
y = a * w**2 + b * w + c
# 求导
[dy_dw] = tape.gradient(y, [w])
print(dy_dw) # 打印出导数
tf.Tensor(10.0, shape=(), dtype=float32)`

**Comment by dragen1860** [comment]
收到，谢谢！
