### ISSUE TITLE
cha06层方式实现 layers.Sequential 报错

### ISSUE THREAD

**Issue by mz2sj** [dragen1860/Deep-Learning-with-TensorFlow-book#70]
`
model = layers.Sequential([
    layers.Dense(256, activation=tf.nn.relu) ,
    layers.Dense(128, activation=tf.nn.relu) ,
    layers.Dense(64, activation=tf.nn.relu) ,
    layers.Dense(10, activation=None) ,
])
`
报错 module 'tensorflow_core.keras.layers' has no attribute 'Sequential'
修改如下运行成功
`
model = tf.keras.models.Sequential([
    layers.Dense(256, activation=tf.nn.relu) ,
    layers.Dense(128, activation=tf.nn.relu) ,
    layers.Dense(64, activation=tf.nn.relu) ,
    layers.Dense(10, activation=None) ,
])
`

**Comment by dragen1860** [comment]
是的，tf又改了API，谢谢你！
