### ISSUE TITLE
10.6梯度传播

### ISSUE THREAD

**Issue by Pealicx** [dragen1860/Deep-Learning-with-TensorFlow-book#71]
第10章，10.6梯度传播
![image](https://user-images.githubusercontent.com/20147750/69496000-403b3b00-0f08-11ea-8f29-530fa0903721.png)
公式右边，第二个偏导分母，我认为应该是：
![image](https://user-images.githubusercontent.com/20147750/69496017-6cef5280-0f08-11ea-8f8b-77bb47a30aaf.png)

**Comment by dragen1860** [comment]
是的，谢谢你！
