### ISSUE TITLE
求助  目标检测   含有building标注的数据集  是哪个啊 

### ISSUE THREAD

**Issue by Deepcong2019** [dragen1860/Deep-Learning-with-TensorFlow-book#73]
书里面有张图片
![ee6ec0fbd858d5fef838ad3b02f3eec](https://user-images.githubusercontent.com/24631762/69525683-9d37ff00-0fa3-11ea-943f-2b65f7f82f2e.png)

**Comment by dragen1860** [comment]
你可以用MS COCO数据集。

**Comment by Deepcong2019** [comment]
@dragen1860 老师  coco数据集好像没有  building这个标注啊
