### ISSUE TITLE
4.9.4矩阵相乘

### ISSUE THREAD

**Issue by Usen-omiga** [dragen1860/Deep-Learning-with-TensorFlow-book#74]
4.9.4矩阵相乘中的a.shape为[4,3,23,32]，代码中的为a = tf.random.normal([4,3,23,32])，以及后面的结果shape = (4,3,28,2),建议修改代码，a = tf.random,normal([4,3,23,32])
很好的书，谢谢

**Comment by dragen1860** [comment]
收到，谢谢！
