### ISSUE TITLE
p4 typo

### ISSUE THREAD

**Issue by dreamlich** [dragen1860/Deep-Learning-with-TensorFlow-book#83]
p4最后一章

考虑 3 维函数𝑧 = 𝑓(𝑥, 𝑦)，函数对自变量𝑥的偏导数记为𝜕𝑧/𝜕x，函数对自变量**𝑥**的偏导数 𝜕z/𝜕𝑦
，则梯度∇𝑓为向量(𝜕𝑥 , 𝜕𝑦)

此处应为函数对自变量y的偏导数

**Comment by huifeiyang** [comment]
right,我也刚发现了,准备发聩

**Comment by dragen1860** [comment]
收到，谢谢
！
