### ISSUE TITLE
【4.5.2 向量】In[43] 中对 layers.Dense没有进行导包

### ISSUE THREAD

**Issue by youngxhui** [dragen1860/Deep-Learning-with-TensorFlow-book#85]
书中的代码并没有对 `tf.keras` 进行处理，这里直接使用 `layers.Dense` 会报错。建议改为 `fc = tf.keras.layers.Dense(3)`

![image](https://user-images.githubusercontent.com/16971804/69719416-6c92c980-114b-11ea-93bd-3b00e14d5657.png)

**Comment by youngxhui** [comment]
该章节 In[45] 同样的问题
![image](https://user-images.githubusercontent.com/16971804/69720771-51758900-114e-11ea-8403-f3c31ce67a7a.png)

**Comment by youngxhui** [comment]
![image](https://user-images.githubusercontent.com/16971804/69721750-808cfa00-1150-11ea-852c-e1f088668cf6.png)

同上

**Comment by dragen1860** [comment]
目前layers, keras等常用包都是默认导入的。谢谢反馈！
