### ISSUE TITLE
ch14/ppo_tf_cartpole.py/报错'Adam' object has no attribute 'apply_gradients'

### ISSUE THREAD

**Issue by mahuangxu** [dragen1860/Deep-Learning-with-TensorFlow-book#93]
第147行：
self.actor_optimizer.apply_gradients(zip(grads, self.actor.trainable_variables))
【报错信息】AttributeError: 'Adam' object has no attribute 'apply_gradients'

**Comment by dragen1860** [comment]
要用tf.keras.optimizers。谢谢。
