### ISSUE TITLE
10.10 节数据加载代码错误

### ISSUE THREAD

**Issue by Varpc** [dragen1860/Deep-Learning-with-TensorFlow-book#97]
![image](https://user-images.githubusercontent.com/29668118/69915618-0b8d2d80-148c-11ea-9cf4-c52b320d407c.png)

此处的`cifar100`应该为`cifar10`，加载cifar10数据集。望作者更正

并且如果使用GPU训练的话，TensorFlow并不会给出具体的错误类型，只会提示未知的错误

**Comment by dragen1860** [comment]
收到，谢谢！
