### ISSUE TITLE
第一章自动梯度， 在colab计算出来的结果有问题

### ISSUE THREAD

**Issue by wxh2013** [dragen1860/Deep-Learning-with-TensorFlow-book#98]
![image](https://user-images.githubusercontent.com/7362131/69915979-2366b080-1490-11ea-929d-88a92dd0f13b.png)
![image](https://user-images.githubusercontent.com/7362131/69915991-4b561400-1490-11ea-928b-a304f4055ba9.png)

**Comment by dragen1860** [comment]
用tf2运行。
