### ISSUE TITLE
p58,TensorFlow 的布尔类型和Python 语言的布尔类型并不对等

### ISSUE THREAD

**Issue by zhaowei0315** [dragen1860/Deep-Learning-with-TensorFlow-book#99]
需要注意的是，TensorFlow 的布尔类型和Python 语言的布尔类型并不对等，不能通用：
In [11]:
a = tf.constant(True) # 创建布尔张量
a == True

在最新版本的tensorflow中，貌似是相等的。
a = tf.constant(True) # 创建布尔张量
if a == True:
    print('True')
else:
    print('False')

打印出的是True

我的tf版本：
tensorflow           2.0.0

**Comment by sfw134** [comment]
是这样的，我也发现了

**Comment by sfw134** [comment]
a == True 为一个值为True的张量<tf.Tensor: id=2, shape=(), dtype=bool, numpy=True>

**Comment by dragen1860** [comment]
收到，谢谢！
